potatofry/potatoapp/urls.py
from django.urls import path
from . import views

app_name = "potatoapp"

urlpatterns = [
    path("", views.index, name="index"),
    path('home',views.home,name='home'),
    path("previous", views.prev, name="previous"),
    path("next", views.next, name="next"),
    path('accounts/login/',views.loginview,name="login"),
	path('logout',views.logout_view),
	path('accounts/sign_up/',views.sign_up,name="signup"),
	path('reset',views.Resethome,name='reset'), 
	path('passwordreset',views.resetPassword,name="passwordreset"),
    path('artist/<int:pk>',views.artist,name='artist'),
    path('library',views.library,name='library')
]

potatofry/potatofry/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('potatoapp.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

potatofry/potatoapp/models.py
from django.db import models

# Create your models here.
class Song(models.Model):
    title= models.TextField()
    artist= models.TextField()
    image= models.ImageField()
    audio_file = models.FileField(blank=True,null=True)
    audio_link = models.CharField(max_length=200,blank=True,null=True)
    duration=models.CharField(max_length=20)

    def __str__(self):
        return self.title #,self.id
    


class Artist(models.Model):
    name= models.TextField()
    image= models.ImageField()

    def __str__(self):
        return self.name #,self.id

potatofry/potatoapp/views.py
from django.shortcuts import render,redirect
from . models import Song,Artist
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required 
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

songlist = []
lost = []
songlistobj = Song.objects.all()
for i in songlistobj:
    songlist.append(i.title)
    lost.append(i.artist)

artistlist = []
artistobj = Artist.objects.all()
for i in artistobj:
    artistlist.append(i.name)

@login_required
def index(request):
    leest = []
    listobj = Song.objects.all()
    artistobj = Artist.objects.all()
    for i in artistobj:
        leest.append(i.name)
    newleest = []
    for i in listobj:
        if i.artist not in leest:
            newleest.append(i)
    context={"song":newleest,'artist':artistobj,'uname':'Good day Mate, See you soon!'}
    return render(request,"list.html",context)


def home(request):
    if request.method == 'POST':

        namee = request.POST['search'].upper()
        
        if namee in songlist:
            song = Song.objects.get(title=namee)
            data = request.POST['data']
            if data == 'list':
                context={"song":song,'home2':'Home','uname':'Good day Mate, See you soon!'}
            else:
                context={"song":song,'home2':'Back','uname':'Good day Mate, See you soon!'}

            return render(request,"index.html",context)
        
        elif namee in artistlist:
            if namee in lost:
            # artsong = Song.objects.filter(artist=namee).first()
                id = Song.objects.filter(artist=namee).first().id
                return redirect('potatoapp:artist',pk=id)
        
            else:
                allsongs = Song.objects.filter(artist=namee)
                return render(request,'artist.html',{'song':allsongs})

        listobj = Song.objects.all()
        artistobj = Artist.objects.all()
        context={"song":listobj,'artist':artistobj,'Search':'Invalid Song or Artist    '}
        return render(request,"library.html",context)
 

def prev(request):
    if request.method == 'POST':

        decider = request.POST['decider']
        art =  request.POST['artist']
        songid = int(request.POST['songid'])
        artobj = Song.objects.filter(artist=art)
        leest = []

        for i in artobj:
            leest.append(i)

        if decider == 'Back':
            for i in leest:
                if i.id == songid:
                    newid = leest.index(i)-1
                    if newid < 0:
                        newid = len(leest)-1
                
                    song = leest[newid]
                    context={"song":song,'home2':'Back','uname':'Good day Mate, See you soon!'}
                    break
        else:
            value = request.POST['prev']
            listobj = Song.objects.all()
            lastobj = 20

            for i in listobj:
                lastobj += 1

            context={"song":listobj}
            currentid = Song.objects.get(title=value).id

            if currentid != 21:
                currentid -= 1
                song = Song.objects.get(id=currentid)
                context={"song":song, 'home2':'Home','uname':'Good day Mate, See you soon!'}
                
            else:
                song = Song.objects.get(id=lastobj)
                context={"song":song , 'home2':'Home','uname':'Good day Mate, See you soon!'}

        return render(request,"index.html",context)
            

def next(request):

    if request.method == 'POST':

        listobj = Song.objects.all()
        lastobj = 20
        for i in listobj:
            lastobj += 1
       
        decider = request.POST['decider']
        art =  request.POST['artist']
        songid = int(request.POST['songid'])
        artobj = Song.objects.filter(artist=art)
        lastart = 0
        leest = []
        for i in artobj:
            lastart += 1
            leest.append(i)

        if decider == 'Back':
            for i in artobj:
                if i.id == songid:
                    newid = leest.index(i)+1
                    if newid > lastart-1:
                        newid = 0
                
                    song = leest[newid]
                    context={"song":song,'home2':'Back','uname':'Good day Mate, See you soon!'}
                    break

        else:
            value = request.POST['next']
            currentid = Song.objects.get(title=value).id
            if currentid != lastobj:
                currentid += 1
                song = Song.objects.get(id=currentid)
                context={"song":song,'home2':'Home','uname':'Good day Mate, See you soon!'}
                
            else:
                song = Song.objects.get(id=21)
                context={"song":song, 'home2':'Home','uname':'Good day Mate, See you soon!'}

        return render(request,"index.html",context)

def loginview(request):
    uname = request.POST['username']
    pwd = request.POST['password']
    user = authenticate(request, username=uname, password=pwd)
    if user is not None:
        login(request, user)
        return redirect('index')
    else:
        return render(request,"login.html")
        
def logout_view(request):
    logout(request)
    return redirect('potatoapp:index')

def sign_up(request):
        uform = UserCreationForm(request.POST)
        if request.method == "POST":
            if uform.is_valid():
                uname = uform.cleaned_data.get('username')
                pwd = uform.cleaned_data.get('password1')
                email=uform.cleaned_data.get('email')
                user1=User.objects.create_user(username=uname,password=pwd,email=email)
                user1.save()
                user = authenticate(request, username=uname, password=pwd)
                login(request,user)
                return redirect('potatoapp:index')
        else:
            form1 = UserCreationForm()
            return render(request, 'registration/sign_up.html', {'form': form1})
        return render(request, 'registration/sign_up.html', {'form': uform})
    
def Resethome(request):
    return render(request,'registration/ResetPassword.html')

def resetPassword(request):
    responseDic={}
    try:
        usern = request.POST['uname']
        # recepient=request.POST['email']
        pwd=request.POST['password']
        #subject="Password reset"
        try:
            user=User.objects.get(username=usern)
            if user is not None:
                user.set_password(pwd)
                user.save()
                #send_mail(subject,message, EMAIL_HOST_USER, [recepient])
                responseDic["errmsg"]="Password Reset Successfully"
                return render(request,"registration/ResetPassword.html",responseDic)
        except Exception as e:
            print(e)
            responseDic["errmsg"]="Email doesnt exist"
            return render(request,"registration/ResetPassword.html",responseDic)
        
    except Exception as e:
        print(e)
        responseDic["errmsg"]="Failed to reset password"
        return render(request,"registration/ResetPassword.html",responseDic)
    
def artist(request,pk=1):
    if request.method == 'POST':
        value = request.POST['art']
        allsongs = Song.objects.filter(artist=value)
    else: 
        value = pk
        song = Song.objects.get(id=value)
        name = song.artist
        allsongs = Song.objects.filter(artist=name)

    return render(request,'artist.html',{'song':allsongs,'uname':'Good day Mate, See you soon!'})

def library(request):
    listobj = Song.objects.all()
    artistobj = Artist.objects.all()
    context={"song":listobj,'artist':artistobj,'uname':'Good day Mate, See you soon!'}
    return render(request,"library.html",context)  

potatofry/potatoapp/templates/artist.html
{% extends './list.html' %}

{% block body %}

<style>

    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: white;
        text-align: center;
        height: 55px;
      }
    </style>

{% endblock %}
{% block bodyone %}
{% endblock %}
{% block title %}
<a href="{% url 'potatoapp:index'%}" style="text-decoration: none; color: black;"><h1>playlist</h1></a>
<br>
{% endblock %}
{% block form %}

<form action="{% url 'potatoapp:home' %}" method="post">
    <span style="display: inline-block;">{{item.duration}}</span>
        {% csrf_token %}
         
        <input type="hidden" value="{{ item.title }}" name="search"> 
        <input type="hidden" name="data" value="artist">
       
        <input  id="playbutton" style="border: none;font-size: 20px; margin-left: 0; width: 150px; font-family:  FontAwesome;" type="submit" value=" &#9654; Listen Now" name="">
    </form>
{% endblock %}

{% block foot %}

<div class="footer" ><p></p>
    <p><a style="text-decoration: none; color: black;" href="{% url 'potatoapp:index' %}">Home</a></p>
</div>

{% endblock %}

potatofry/potatoapp/templates/index.html
{% extends './list.html' %}

   {% load static %}

    {% block styles %}
    <link rel="stylesheet" href="{% static './index.css' %}"> 
    {% endblock %}

    {% block body %}
    {% endblock %}

{% block bodyone %}

    <div class="container">
        <div class="music-player">
        <div class="music-player-content">
            <div class="cover">
                <img src="{{song.image.url}}" alt="Album Cover">
            </div>
            <div class="music-controls">
                <form action="previous" method="post">
                    {% csrf_token %}
                <button class="control-button" name="prev" value="{{ song.title }}">&#9668;</button>
                <input type="hidden" name="decider" value="{{ home2 }}" >
                <input type="hidden" name="artist" value="{{ song.artist }}">
                <input type="hidden" name="songid" value="{{ song.id }}">
               </form>

                <!-- <button class="control-button" id="mybutton" onClick="togglePlay()"></button> -->
                <input style="width: 76px; margin: 0 12px; height: 45px;" class="control-button" id="mybutton" onClick="togglePlay()" value="play" type="submit">

                <form action="next" method="post">
                    {% csrf_token %}
                <button class="control-button" name="next" value="{{ song.title }}">&#9654;</button>
                <input type="hidden" name="decider" value="{{ home2 }}" >
                <input type="hidden" name="artist" value="{{ song.artist }}">
                <input type="hidden" name="songid" value="{{ song.id }}">
            </form>
            </div><br>
            <div class="music-details">
                <h2 class="music-title"> {{song.title}}</h2>
                <p class="music-artist"> {{song.artist}}</p>
            </div>
            <center><a id='none' href='' style="text-decoration: none;color: #3DB2FF">{{ home2 }}</a></center>
        </div><br>
        <center>
        <audio id="buzzer" controls class="audio-player" style="background-color: transparent;">
            <source src="{% if song.audio_file %}{{song.audio_file.url}} {% else %} {{song.audio_link}} {% endif %}" type="audio/mp3">
        </audio>
        </center>

    </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    <script>
        
        $(document).ready(function(){
        const username = "{{ home2|escapejs }}";
        const artist = "{{ song.artist|escapejs }}";
        if (username == 'Home'){
            $('#none').attr("href","{% url 'potatoapp:index' %}");
        }
        else {
            $('#none').attr("href",'artist/{{ song.id }}');
        }
    });

    </script>

    <script>
    $(document).ready(function(){
      $("#mybutton").click(function(){
        $(this).val($(this).val() == 'play' ? 'pause' : 'play');
      });
    });
    </script>

    <script>

        var buzzer = document.getElementById("buzzer");
        var isPlaying = false;

        function togglePlay() {
        isPlaying ? buzzer.pause() : buzzer.play();
        };

        buzzer.onplaying = function() {
        isPlaying = true;
        };
        buzzer.onpause = function() {
        isPlaying = false;
        };

    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    {% endblock %}
    {% block footer %}
    {% endblock %}

potatofry/potatoapp/templates/library.html
{% extends './list.html' %}

{% block body %}

<style>

.footer {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    background-color: white;
    text-align: center;
    height: 55px;
  }
</style>

{% endblock %}
{% block bodyone %}
{% endblock %}
{% block title %}
<a href="{% url 'potatoapp:index'%}" style="text-decoration: none;color: black;"><h1>your library</h1></a>
<br>
{% endblock %}

{% block foot %}

<div class="footer" ><p></p>
    <p><a style="text-decoration: none; color: black;" href="{% url 'potatoapp:index' %}">Home</a></p>
</div>

{% endblock %}

potatofry/potatoapp/templates/list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PotatoFry</title>
    {% block styles %}
    <link rel="stylesheet" href="{% static './musiclist.css' %}"> 
    {% endblock %}
    <link rel="icon" type="image/x-icon" href="{% static './favicon.ico' %}">
    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% block body %}
    <style>
        .carousel-inner > .carousel-item > img,
        .carousel-inner > .carousel-item > a > img {
            display: block;
            max-width: 100%;
            height: 440px !important;
        }
        </style>
      {% endblock %}
</head>
<body>
      
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'potatoapp:index' %}">PotatoFry</a>
            <a style="margin-left: 12%;" class="nav-link active" aria-current="page" href="{% url 'potatoapp:library' %}">soundtracks</a>

            <ul class="nav justify-content-end">
              <li class="nav-item">

              <form  class="d-flex" role="search" method="post" action="{% url 'potatoapp:home' %}">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="{{ Search }}Search" aria-label="Search" name="search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
                <input type="hidden" name="data" value="list">
              </form>

             </li>

             <li class="nav-item"></li>
                <button style="width: 50px;" class="btn btn-secondary-emphasis" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasTop" aria-controls="offcanvasTop"><span class="navbar-toggler-icon"></span></button>

                  <div style="height: 165px; border-radius: 20px;" class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasTop" aria-labelledby="offcanvasTopLabel">
                      <div class="offcanvas-header">
                          <center><h5 style="padding-top: 2% ";>{{uname}}</h5></center>
                          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                      </div>
                      <div class="offcanvas-body">
                          <center><button class="btn btn-success"><a style="color: white;" class="nav-link active" aria-current="page" href="logout">LogOut</a></button></center>
                      </div>
                  </div>

              </li>
            </ul>

        </div>
      </nav>

{% block bodyone %}

      <div id="carouselExampleCaptions" class="carousel slide">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{%static '/never.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>RADIOACTIVE</h5>
              <p>COMING SOON!!!</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{%static '/neverclose.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>NEVER CLOSE OUR EYES</h5>
              <p>COMING SOON!!!</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{%static '/till.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5 style="color: white;">DUSK TILL DAWN</h5>
              <p style="color: white;">COMING SOON!!!</p>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div> 
      
  <form action="artist/1" method="post">
      {% csrf_token %}
      <div class="container-fluid" style="background-color: black;">
        <div class="row">
          {% for item in artist %}
            <div class="col-2">
                <div style="background-color: black; color: aliceblue;" class="card card-block"><img style="height: 235px;  border-radius: 25px;" src="{{ item.image.url}}" alt=""><center><p></p><input type="submit" value="{{ item.name }}" name="art" style="border: none; background-color: black; color: white;"><p></p></center></div>
            </div>
          {% endfor %}
        </div>
    </div>
  </form>
 

  {% endblock %}
  
  {% block footer %}
    <div class="container">
        <div class="music-list"><br>
          {% block title %}
            <h1>New Releases</h1><br>
            {% endblock %}
            <ul>
                {% for item in song %}
                <li class="music-item">
                    <img src="{{item.image.url}}">
                    <div class="music-details">
                        <h3>{{item.title}}</h3>
                        <p>{{item.artist}}</p>
                  {% block form %}
                      <form action="home" method="post">
                        <span style="display: inline-block;">{{item.duration}}</span>
                            {% csrf_token %}
                        
                            <input type="hidden" value="{{ item.title }}" name="search"> 
                            <input type="hidden" name="data" value="list">
                           
                            <!-- <input  id="playbutton" style="border: none; font-family:  FontAwesome;" type="submit" value="&#9654;" name=""> -->
                            <input  id="playbutton" style="border: none;font-size: 20px; font-family: FontAwesome; margin-left: 0; width: 150px; color: #3085C3;" type="submit" value=" &#9654; Listen Now" name="">
                        </form>
                  {% endblock %}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
  crossorigin="anonymous"></script>
  {% endblock %}
  {% block foot %}
  {% endblock %}
</body>
</html>